# Generated by Django 4.2.26 on 2025-11-15 19:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="facebook_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="browser_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="browser_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="matched_via",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="os_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="screen_resolution",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="visitor",
            name="timezone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="EnrichmentData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("ip_addresses", models.JSONField(blank=True, default=list)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("job_title", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(default="csv_upload", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_data",
                        to="tracking.site",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Enrichment data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="enrichment_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="tracking.enrichmentdata",
            ),
        ),
        migrations.AddIndex(
            model_name="enrichmentdata",
            index=models.Index(
                fields=["site", "email"], name="tracking_en_site_id_34d403_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrichmentdata",
            unique_together={("site", "email")},
        ),
    ]
