# Generated by Django 4.2.26 on 2025-11-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tracking",
            "0003_event_referrer_event_utm_campaign_event_utm_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("page_view", "Page View"),
                    ("cart_view", "Cart View"),
                    ("cart_add", "Add to Cart"),
                    ("checkout_start", "Checkout Started"),
                    ("purchase", "Purchase"),
                    ("form_submit", "Form Submit"),
                    ("custom", "Custom Event"),
                    ("browse_abandonment", "Browse Abandonment"),
                    ("product_view", "Product View"),
                    ("product_abandonment", "Product Abandonment"),
                    ("cart_abandonment", "Cart Abandonment"),
                    ("checkout_abandonment", "Checkout Abandonment"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
