# Generated by Django 4.2.26 on 2025-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrichmentdata",
            name="browser_fingerprints",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="enrichmentdata",
            name="phone_numbers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="enrichmentdata",
            name="user_agents",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
